In [322]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
import MLP

# Iris Data Set

## Подготовка данных

In [343]:
dataframe = pd.read_csv("../data/iris.csv")

In [344]:
dataframe

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [325]:
dataset = dataframe.values

In [326]:
X = dataset[:, 0:4]
y = dataset[:, 4]

In [327]:
# Iris-setosa кодируется как класс 0
# Iris-versicolor – класс 1 
# Iris-virginica как класс 2 
encoder = LabelEncoder()
encoder.fit(Y)
y = encoder.transform(Y)

In [328]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [329]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y)

In [330]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [331]:
X_train.shape

(104, 4)

##  Классификация MLP

In [338]:
mlp = MLP.MLP(4, 5, 3, learning_rate=0.1, max_epochs=2000, verbose=3)

In [339]:
mlp.fit(X_train, y_train)

In [340]:
y_pred = mlp.predict(X_test)

In [341]:
y_pred

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1], dtype=int64)

In [342]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11  4  0]
 [ 1 14  0]
 [ 0 15  0]]
              precision    recall  f1-score   support

           0       0.92      0.73      0.81        15
           1       0.42      0.93      0.58        15
           2       0.00      0.00      0.00        15

    accuracy                           0.56        45
   macro avg       0.45      0.56      0.47        45
weighted avg       0.45      0.56      0.47        45



D:\Users\DZHALIL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\DZHALIL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\DZHALIL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#  Titanik DataSet

## Подготовка данных

In [476]:
dataframe = pd.read_csv("../data/titanic.csv")

In [477]:
dataframe

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [478]:
dataframe.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1,inplace=True)
dataframe.fillna(dataframe.mean(), inplace=True)
dataframe

Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [479]:
# male кодируется как класс 0
# female – класс 1 
encoder = LabelEncoder()
encoder.fit(dataframe['Sex'])
dataframe['Sex'] = encoder.transform(dataframe['Sex'])

In [483]:
# C кодируется как класс 0
# Q – класс 1 
# S – класс 2 
encoder = LabelEncoder()
encoder.fit(dataframe['Embarked'])
dataframe['Embarked'] = encoder.transform(dataframe['Embarked'])

In [484]:
y = dataframe['Survived']
X = dataframe[dataframe.columns[1:dataframe.shape[0]]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)

In [485]:
print(X)

     Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    1  22.000000      1      0   7.2500         2
1         1    0  38.000000      1      0  71.2833         0
2         3    0  26.000000      0      0   7.9250         2
3         1    0  35.000000      1      0  53.1000         2
4         3    1  35.000000      0      0   8.0500         2
..      ...  ...        ...    ...    ...      ...       ...
886       2    1  27.000000      0      0  13.0000         2
887       1    0  19.000000      0      0  30.0000         2
888       3    0  29.699118      1      2  23.4500         2
889       1    1  26.000000      0      0  30.0000         0
890       3    1  32.000000      0      0   7.7500         1

[891 rows x 7 columns]


## Классификация MLP

In [486]:
mlp = MLP.MLP(X_train.shape[1], 15, 2, learning_rate=0.1, max_epochs=2000, verbose=3)

In [487]:
mlp.fit(X_train, y_train)

ValueError: could not convert string to float: 'Pclass'

In [451]:
dataframe.to_csv('file1.csv')

# My DataSet

## Подготовка данных

In [434]:
df = pd.read_csv('../data/extention_ZAlizadeh_san_preprocessed.csv') 

In [435]:
del df['Unnamed: 0']

In [436]:
df.head(10)

Age  Weight  Length  Sex        BMI  DM  HTN  Current Smoker  EX-Smoker  \
0   53      90     175    1  29.387755   0    1               1          0   
1   67      70     157    2  28.398718   0    1               0          0   
2   54      54     164    1  20.077335   0    0               1          0   
3   66      67     158    2  26.838648   0    1               0          0   
4   50      87     153    2  37.165193   0    1               0          0   
5   50      75     175    1  24.489796   0    0               1          0   
6   55      80     165    1  29.384757   0    0               0          1   
7   72      80     175    1  26.122449   1    0               1          0   
8   58      84     163    2  31.615793   0    0               0          0   
9   60      71     170    1  24.567474   1    0               0          0   

   FH  ...  Lymph  Neut  PLT  EF-TTE  Region RWMA  VHD  LAD  LCX  RCA  Cath  
0   0  ...     39    52  261      50            0    2    1    0    1     0  
1   0  ...     38    55  165      40            4    2    1    1    0     0  
2   0  ...     38    60  230      40            2    0    1    0    0     0  
3   0  ...     18    72  742      55            0    3    0    0    0     1  
4   0  ...     55    39  274      50            0    3    0    0    0     1  
5   0  ...     26    66  194      50            0    2    1    1    1     0  
6   0  ...     58    33  292      40            4    0    1    0    0     0  
7   0  ...     25    74  410      45            4    0    1    1    1     0  
8   0  ...     49    50  370      50            0    2    0    0    0     1  
9   0  ...     55    42  380      40            2    2    0    1    1     0  

[10 rows x 59 columns]

In [437]:
X = df.iloc[:,:26].values
y = df.iloc[:,27].values

In [438]:
print (df.shape, X.shape, y.shape)

(303, 59) (303, 26) (303,)


In [439]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)

In [440]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Классификация MLP

In [446]:
mlp = MLP.MLP(X_train.shape[1], 25, 2, learning_rate=0.1, max_epochs=2000, verbose=3)

In [447]:
mlp.fit(X_train, y_train)

In [448]:
y_pred = mlp.predict(X_test)

In [449]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [450]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[39 14]
 [12 11]]
              precision    recall  f1-score   support

           0       0.76      0.74      0.75        53
           1       0.44      0.48      0.46        23

    accuracy                           0.66        76
   macro avg       0.60      0.61      0.60        76
weighted avg       0.67      0.66      0.66        76

